"""initial schema

Revision ID: 914e5fe1c754
Revises:
Create Date: 2026-04-25 13:16:36.098265

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '914e5fe1c754'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_parkir',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('emoney_readers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('serial_port', sa.String(length=50), nullable=False),
    sa.Column('baudrate', sa.Integer(), nullable=False),
    sa.Column('mid', sa.String(length=20), nullable=True),
    sa.Column('tid', sa.String(length=20), nullable=True),
    sa.Column('encrypted_init_key', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.String(length=50), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('emoney_settlements',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('bank_response_file', sa.String(length=255), nullable=True),
    sa.Column('bank_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bank_response_code', sa.String(length=50), nullable=True),
    sa.Column('bank_response_message', sa.Text(), nullable=True),
    sa.Column('file_content_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emoney_settlements_batch_date'), 'emoney_settlements', ['batch_date'], unique=False)
    op.create_table('health_checks',
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_checks_checked_at'), 'health_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_health_checks_component'), 'health_checks', ['component'], unique=False)
    op.create_table('member_groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('shifts',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('snapshots',
    sa.Column('parking_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('gate_id', sa.BigInteger(), nullable=False),
    sa.Column('gate_type', sa.String(length=10), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('detected_plate', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('camera_name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_detected_plate'), 'snapshots', ['detected_plate'], unique=False)
    op.create_index(op.f('ix_snapshots_gate_id'), 'snapshots', ['gate_id'], unique=False)
    op.create_index(op.f('ix_snapshots_parking_transaction_id'), 'snapshots', ['parking_transaction_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('base_tariff', sa.Integer(), nullable=False),
    sa.Column('hourly_rate', sa.Integer(), nullable=False),
    sa.Column('max_daily_cap', sa.Integer(), nullable=False),
    sa.Column('lost_ticket_penalty', sa.Integer(), nullable=False),
    sa.Column('overnight_mode', sa.String(length=20), nullable=False),
    sa.Column('overnight_tariff', sa.Integer(), nullable=False),
    sa.Column('is_progressive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('gate_ins',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('area_parkir_id', sa.BigInteger(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('controller_host', sa.String(length=100), nullable=True),
    sa.Column('controller_port', sa.Integer(), nullable=True),
    sa.Column('gate_mode', sa.String(length=20), nullable=False),
    sa.Column('emoney_minimum_balance', sa.Integer(), nullable=False),
    sa.Column('print_decision_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('has_close_sensor', sa.Boolean(), nullable=False),
    sa.Column('gate_close_duration_ms', sa.Integer(), nullable=False),
    sa.Column('open_command', sa.String(length=50), nullable=True),
    sa.Column('close_command', sa.String(length=50), nullable=True),
    sa.Column('pulse_duration_ms', sa.Integer(), nullable=True),
    sa.Column('gate_open_timeout_s', sa.Integer(), nullable=True),
    sa.Column('sensor_stuck_s', sa.Integer(), nullable=True),
    sa.Column('audio_module', sa.String(length=50), nullable=True),
    sa.Column('led_display', sa.String(length=50), nullable=True),
    sa.Column('printer_name', sa.String(length=100), nullable=True),
    sa.Column('printer_type', sa.String(length=20), nullable=True),
    sa.Column('camera_url', sa.String(length=500), nullable=True),
    sa.Column('camera_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_parkir_id'], ['area_parkir.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('gate_outs',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('area_parkir_id', sa.BigInteger(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('controller_host', sa.String(length=100), nullable=True),
    sa.Column('controller_port', sa.Integer(), nullable=True),
    sa.Column('emoney_reader_id', sa.BigInteger(), nullable=True),
    sa.Column('payment_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('has_close_sensor', sa.Boolean(), nullable=False),
    sa.Column('gate_close_duration_ms', sa.Integer(), nullable=False),
    sa.Column('open_command', sa.String(length=50), nullable=True),
    sa.Column('close_command', sa.String(length=50), nullable=True),
    sa.Column('pulse_duration_ms', sa.Integer(), nullable=True),
    sa.Column('gate_open_timeout_s', sa.Integer(), nullable=True),
    sa.Column('sensor_stuck_s', sa.Integer(), nullable=True),
    sa.Column('audio_module', sa.String(length=50), nullable=True),
    sa.Column('led_display', sa.String(length=50), nullable=True),
    sa.Column('printer_name', sa.String(length=100), nullable=True),
    sa.Column('printer_type', sa.String(length=20), nullable=True),
    sa.Column('camera_url', sa.String(length=500), nullable=True),
    sa.Column('camera_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.String(length=50), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_parkir_id'], ['area_parkir.id'], ),
    sa.ForeignKeyConstraint(['emoney_reader_id'], ['emoney_readers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('members',
    sa.Column('card_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type_id', sa.BigInteger(), nullable=True),
    sa.Column('member_group_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('last_entry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_group_id'], ['member_groups.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_card_number'), 'members', ['card_number'], unique=True)
    op.create_index(op.f('ix_members_plate_number'), 'members', ['plate_number'], unique=False)
    op.create_table('shift_emoney_snapshots',
    sa.Column('shift_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('lost_contact_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_emoney_snapshots_shift_id'), 'shift_emoney_snapshots', ['shift_id'], unique=False)
    op.create_index(op.f('ix_shift_emoney_snapshots_snapshot_date'), 'shift_emoney_snapshots', ['snapshot_date'], unique=False)
    op.create_table('member_renewals',
    sa.Column('member_id', sa.BigInteger(), nullable=False),
    sa.Column('renewed_by', sa.BigInteger(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['renewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_renewals_member_id'), 'member_renewals', ['member_id'], unique=False)
    op.create_table('parking_transactions',
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type_id', sa.BigInteger(), nullable=True),
    sa.Column('gate_in_id', sa.BigInteger(), nullable=True),
    sa.Column('gate_out_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('fee', sa.Integer(), nullable=True),
    sa.Column('paid_amount', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.BigInteger(), nullable=True),
    sa.Column('emoney_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('shift_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('exit_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_lost_ticket', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gate_in_id'], ['gate_ins.id'], ),
    sa.ForeignKeyConstraint(['gate_out_id'], ['gate_outs.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_transactions_barcode'), 'parking_transactions', ['barcode'], unique=True)
    op.create_index(op.f('ix_parking_transactions_card_number'), 'parking_transactions', ['card_number'], unique=False)
    op.create_index(op.f('ix_parking_transactions_emoney_transaction_id'), 'parking_transactions', ['emoney_transaction_id'], unique=False)
    op.create_index(op.f('ix_parking_transactions_entry_snapshot_id'), 'parking_transactions', ['entry_snapshot_id'], unique=False)
    op.create_index(op.f('ix_parking_transactions_exit_snapshot_id'), 'parking_transactions', ['exit_snapshot_id'], unique=False)
    op.create_index(op.f('ix_parking_transactions_member_id'), 'parking_transactions', ['member_id'], unique=False)
    op.create_index(op.f('ix_parking_transactions_plate_number'), 'parking_transactions', ['plate_number'], unique=False)
    op.create_index(op.f('ix_parking_transactions_status'), 'parking_transactions', ['status'], unique=False)
    op.create_index('uq_active_card', 'parking_transactions', ['card_number'], unique=True, postgresql_where=sa.text("status = 'ACTIVE' AND card_number IS NOT NULL"))
    op.create_table('abandoned_vehicle_logs',
    sa.Column('gate_out_id', sa.BigInteger(), nullable=False),
    sa.Column('parking_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('waiting_seconds', sa.Integer(), nullable=False),
    sa.Column('resolution_type', sa.String(length=30), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gate_out_id'], ['gate_outs.id'], ),
    sa.ForeignKeyConstraint(['parking_transaction_id'], ['parking_transactions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abandoned_vehicle_logs_gate_out_id'), 'abandoned_vehicle_logs', ['gate_out_id'], unique=False)
    op.create_index(op.f('ix_abandoned_vehicle_logs_parking_transaction_id'), 'abandoned_vehicle_logs', ['parking_transaction_id'], unique=False)
    op.create_table('emoney_transactions',
    sa.Column('parking_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('card_number', sa.String(length=32), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('amount_deducted', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('transaction_counter', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_response_hex', sa.Text(), nullable=True),
    sa.Column('settlement_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correction_note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_transaction_id'], ['parking_transactions.id'], ),
    sa.ForeignKeyConstraint(['settlement_batch_id'], ['emoney_settlements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_correction', 'emoney_transactions', ['created_at'], unique=False, postgresql_where=sa.text("status IN ('LOST_CONTACT', 'CORRECTION_FAILED')"))
    op.create_index('idx_unsettled_emoney', 'emoney_transactions', ['created_at'], unique=False, postgresql_where=sa.text("settlement_batch_id IS NULL AND status = 'SUCCESS'"))
    op.create_index(op.f('ix_emoney_transactions_card_number'), 'emoney_transactions', ['card_number'], unique=False)
    op.create_index(op.f('ix_emoney_transactions_parking_transaction_id'), 'emoney_transactions', ['parking_transaction_id'], unique=False)
    op.create_index(op.f('ix_emoney_transactions_settlement_batch_id'), 'emoney_transactions', ['settlement_batch_id'], unique=False)
    op.create_index(op.f('ix_emoney_transactions_status'), 'emoney_transactions', ['status'], unique=False)
    op.create_table('manual_open_logs',
    sa.Column('gate_id', sa.BigInteger(), nullable=False),
    sa.Column('gate_type', sa.String(length=10), nullable=False),
    sa.Column('opened_by', sa.BigInteger(), nullable=False),
    sa.Column('parking_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parking_transaction_id'], ['parking_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_open_logs_gate_id'), 'manual_open_logs', ['gate_id'], unique=False)
    op.create_table('operator_alerts',
    sa.Column('gate_type', sa.String(length=10), nullable=False),
    sa.Column('gate_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('parking_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_transaction_id'], ['parking_transactions.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_alerts_alert_type'), 'operator_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_operator_alerts_gate_id'), 'operator_alerts', ['gate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_alerts_gate_id'), table_name='operator_alerts')
    op.drop_index(op.f('ix_operator_alerts_alert_type'), table_name='operator_alerts')
    op.drop_table('operator_alerts')
    op.drop_index(op.f('ix_manual_open_logs_gate_id'), table_name='manual_open_logs')
    op.drop_table('manual_open_logs')
    op.drop_index(op.f('ix_emoney_transactions_status'), table_name='emoney_transactions')
    op.drop_index(op.f('ix_emoney_transactions_settlement_batch_id'), table_name='emoney_transactions')
    op.drop_index(op.f('ix_emoney_transactions_parking_transaction_id'), table_name='emoney_transactions')
    op.drop_index(op.f('ix_emoney_transactions_card_number'), table_name='emoney_transactions')
    op.drop_index('idx_unsettled_emoney', table_name='emoney_transactions', postgresql_where=sa.text("settlement_batch_id IS NULL AND status = 'SUCCESS'"))
    op.drop_index('idx_pending_correction', table_name='emoney_transactions', postgresql_where=sa.text("status IN ('LOST_CONTACT', 'CORRECTION_FAILED')"))
    op.drop_table('emoney_transactions')
    op.drop_index(op.f('ix_abandoned_vehicle_logs_parking_transaction_id'), table_name='abandoned_vehicle_logs')
    op.drop_index(op.f('ix_abandoned_vehicle_logs_gate_out_id'), table_name='abandoned_vehicle_logs')
    op.drop_table('abandoned_vehicle_logs')
    op.drop_index('uq_active_card', table_name='parking_transactions', postgresql_where=sa.text("status = 'ACTIVE' AND card_number IS NOT NULL"))
    op.drop_index(op.f('ix_parking_transactions_status'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_plate_number'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_member_id'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_exit_snapshot_id'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_entry_snapshot_id'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_emoney_transaction_id'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_card_number'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_barcode'), table_name='parking_transactions')
    op.drop_table('parking_transactions')
    op.drop_index(op.f('ix_member_renewals_member_id'), table_name='member_renewals')
    op.drop_table('member_renewals')
    op.drop_index(op.f('ix_shift_emoney_snapshots_snapshot_date'), table_name='shift_emoney_snapshots')
    op.drop_index(op.f('ix_shift_emoney_snapshots_shift_id'), table_name='shift_emoney_snapshots')
    op.drop_table('shift_emoney_snapshots')
    op.drop_index(op.f('ix_members_plate_number'), table_name='members')
    op.drop_index(op.f('ix_members_card_number'), table_name='members')
    op.drop_table('members')
    op.drop_table('gate_outs')
    op.drop_table('gate_ins')
    op.drop_table('vehicle_types')
    op.drop_table('users')
    op.drop_index(op.f('ix_snapshots_parking_transaction_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_gate_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_detected_plate'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('member_groups')
    op.drop_index(op.f('ix_health_checks_component'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_checked_at'), table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_emoney_settlements_batch_date'), table_name='emoney_settlements')
    op.drop_table('emoney_settlements')
    op.drop_table('emoney_readers')
    op.drop_table('area_parkir')
    # ### end Alembic commands ###
