"""add settlement sftp config and emoney_reader_id

Revision ID: c61aa0103c8c
Revises: b7b386fcd5bc
Create Date: 2026-04-26 08:35:42.639755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61aa0103c8c'
down_revision: Union[str, None] = 'b7b386fcd5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emoney_readers', sa.Column('sftp_host', sa.String(length=100), nullable=True))
    op.add_column('emoney_readers', sa.Column('sftp_username', sa.String(length=100), nullable=True))
    op.add_column('emoney_readers', sa.Column('sftp_key_path', sa.String(length=255), nullable=True))
    op.add_column('emoney_readers', sa.Column('sftp_remote_path', sa.String(length=255), nullable=True))
    op.add_column('emoney_transactions', sa.Column('emoney_reader_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_emoney_transactions_emoney_reader_id'), 'emoney_transactions', ['emoney_reader_id'], unique=False)
    op.create_foreign_key(None, 'emoney_transactions', 'emoney_readers', ['emoney_reader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emoney_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_emoney_transactions_emoney_reader_id'), table_name='emoney_transactions')
    op.drop_column('emoney_transactions', 'emoney_reader_id')
    op.drop_column('emoney_readers', 'sftp_remote_path')
    op.drop_column('emoney_readers', 'sftp_key_path')
    op.drop_column('emoney_readers', 'sftp_username')
    op.drop_column('emoney_readers', 'sftp_host')
    # ### end Alembic commands ###
