"""add_indexes_on_entry_time_and_exit_time

Revision ID: f7999809b648
Revises: e1f655046e3b
Create Date: 2026-05-31 00:58:43.287674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7999809b648'
down_revision: Union[str, None] = 'e1f655046e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_renewals_member_id'), table_name='member_renewals')
    op.drop_table('member_renewals')
    op.drop_index(op.f('ix_health_checks_checked_at'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_component'), table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_shift_emoney_snapshots_shift_id'), table_name='shift_emoney_snapshots')
    op.drop_index(op.f('ix_shift_emoney_snapshots_snapshot_date'), table_name='shift_emoney_snapshots')
    op.drop_table('shift_emoney_snapshots')
    op.drop_constraint(op.f('fk_abandoned_vehicle_logs_gate_out'), 'abandoned_vehicle_logs', type_='foreignkey')
    op.create_foreign_key(None, 'abandoned_vehicle_logs', 'gates', ['gate_out_id'], ['id'])
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.drop_index(op.f('ix_gates_direction'), table_name='gates')
    op.drop_index(op.f('ix_gates_pos_id'), table_name='gates')
    op.create_index(op.f('ix_parking_transactions_entry_time'), 'parking_transactions', ['entry_time'], unique=False)
    op.create_index(op.f('ix_parking_transactions_exit_time'), 'parking_transactions', ['exit_time'], unique=False)
    op.create_index(op.f('ix_parking_transactions_gate_in_id'), 'parking_transactions', ['gate_in_id'], unique=False)
    op.create_index(op.f('ix_parking_transactions_gate_out_id'), 'parking_transactions', ['gate_out_id'], unique=False)
    op.drop_constraint(op.f('fk_parking_transactions_gate_in'), 'parking_transactions', type_='foreignkey')
    op.drop_constraint(op.f('fk_parking_transactions_gate_out'), 'parking_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'parking_transactions', 'gates', ['gate_out_id'], ['id'])
    op.create_foreign_key(None, 'parking_transactions', 'gates', ['gate_in_id'], ['id'])
    op.drop_index(op.f('ix_pos_default_gate_id'), table_name='pos')
    op.drop_index(op.f('ix_pos_last_seen_at'), table_name='pos')
    op.drop_index(op.f('ix_printers_pos_id'), table_name='printers')
    op.drop_constraint(op.f('setup_sessions_session_token_key'), 'setup_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('setup_sessions_session_token_key'), 'setup_sessions', ['session_token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_printers_pos_id'), 'printers', ['pos_id'], unique=False)
    op.create_index(op.f('ix_pos_last_seen_at'), 'pos', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_pos_default_gate_id'), 'pos', ['default_gate_id'], unique=False)
    op.drop_constraint(None, 'parking_transactions', type_='foreignkey')
    op.drop_constraint(None, 'parking_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_parking_transactions_gate_out'), 'parking_transactions', 'gates', ['gate_out_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_parking_transactions_gate_in'), 'parking_transactions', 'gates', ['gate_in_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_parking_transactions_gate_out_id'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_gate_in_id'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_exit_time'), table_name='parking_transactions')
    op.drop_index(op.f('ix_parking_transactions_entry_time'), table_name='parking_transactions')
    op.create_index(op.f('ix_gates_pos_id'), 'gates', ['pos_id'], unique=False)
    op.create_index(op.f('ix_gates_direction'), 'gates', ['direction'], unique=False)
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_constraint(None, 'abandoned_vehicle_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_abandoned_vehicle_logs_gate_out'), 'abandoned_vehicle_logs', 'gates', ['gate_out_id'], ['id'], ondelete='CASCADE')
    op.create_table('shift_emoney_snapshots',
    sa.Column('shift_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('snapshot_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('card_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('transaction_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lost_contact_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('shift_emoney_snapshots_shift_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_emoney_snapshots_pkey'))
    )
    op.create_index(op.f('ix_shift_emoney_snapshots_snapshot_date'), 'shift_emoney_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_shift_emoney_snapshots_shift_id'), 'shift_emoney_snapshots', ['shift_id'], unique=False)
    op.create_table('health_checks',
    sa.Column('component', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('health_checks_pkey'))
    )
    op.create_index(op.f('ix_health_checks_component'), 'health_checks', ['component'], unique=False)
    op.create_index(op.f('ix_health_checks_checked_at'), 'health_checks', ['checked_at'], unique=False)
    op.create_table('member_renewals',
    sa.Column('member_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('renewed_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('valid_from', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('valid_until', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount_paid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('member_renewals_member_id_fkey')),
    sa.ForeignKeyConstraint(['renewed_by'], ['users.id'], name=op.f('member_renewals_renewed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('member_renewals_pkey'))
    )
    op.create_index(op.f('ix_member_renewals_member_id'), 'member_renewals', ['member_id'], unique=False)
    # ### end Alembic commands ###
