#!/usr/bin/env bash
# Write stable /dev/parking-gate-<CODE> symlinks for every serial gate in DB.
#
# Why: USB tty devices renumber on reboot (/dev/ttyUSB0 may become ttyUSB1).
# Daemons then fail to open the configured port. Udev rules pin a stable
# symlink by USB vendor/product/serial so the path the operator entered in
# the wizard keeps working forever.
#
# Usage:
#   sudo ./scripts/write-udev-rules.sh                # generate from DB
#   sudo ./scripts/write-udev-rules.sh --dry-run      # preview only
#   sudo ./scripts/write-udev-rules.sh --from-json FILE
#
# JSON form expected (one record per gate):
#   [{"code":"GOUT01","device":"/dev/ttyUSB0"}, ...]

set -euo pipefail

RULES_FILE="/etc/udev/rules.d/99-parking-gates.rules"
DRY_RUN=0
FROM_JSON=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    --from-json) FROM_JSON="$2"; shift ;;
    -h|--help) sed -n '1,20p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
  shift
done

if [[ $EUID -ne 0 && $DRY_RUN -eq 0 ]]; then
  echo "must be root (or pass --dry-run)" >&2
  exit 1
fi

# Resolve gate list ----------------------------------------------------------

declare -a PAIRS=()  # entries: "CODE|/dev/ttyUSBX"

load_from_db() {
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  cd "$script_dir/.."
  # Use venv python if present
  local py=".venv/bin/python"
  [[ -x "$py" ]] || py="python3"
  "$py" -c '
import asyncio, json, sys
sys.path.insert(0, ".")
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine
from shared.config import get_settings

async def main():
    eng = create_async_engine(get_settings().database_url)
    async with eng.connect() as c:
        rows = (await c.execute(text(
            "SELECT code, controller_device FROM gates "
            "WHERE controller_device IS NOT NULL AND is_active = true"
        ))).all()
    await eng.dispose()
    print(json.dumps([{"code": r[0], "device": r[1]} for r in rows]))

asyncio.run(main())
'
}

if [[ -n "$FROM_JSON" ]]; then
  json_text="$(cat "$FROM_JSON")"
else
  json_text="$(load_from_db)"
fi

# Parse JSON without jq dep
mapfile -t PAIRS < <(python3 -c '
import json, sys
for r in json.loads(sys.stdin.read()):
    print(f"{r[\"code\"]}|{r[\"device\"]}")
' <<<"$json_text")

if [[ ${#PAIRS[@]} -eq 0 ]]; then
  echo "no serial gates found — nothing to write" >&2
  exit 0
fi

# Build rules ----------------------------------------------------------------

probe_attrs() {
  # Print: VENDOR PRODUCT SERIAL for the given /dev/ttyUSBX
  local dev="$1"
  if [[ ! -e "$dev" ]]; then
    echo "MISSING MISSING MISSING"; return
  fi
  local out
  out="$(udevadm info -a -n "$dev" 2>/dev/null)" || { echo "ERR ERR ERR"; return; }
  local v p s
  v="$(awk -F'"' '/ATTRS{idVendor}/ {print $2; exit}' <<<"$out")"
  p="$(awk -F'"' '/ATTRS{idProduct}/ {print $2; exit}' <<<"$out")"
  s="$(awk -F'"' '/ATTRS{serial}/ {print $2; exit}' <<<"$out")"
  echo "${v:-NONE} ${p:-NONE} ${s:-NONE}"
}

tmpfile="$(mktemp)"
trap 'rm -f "$tmpfile"' EXIT

{
  echo "# Generated by scripts/write-udev-rules.sh on $(date -Iseconds)"
  echo "# DO NOT EDIT — re-run the script to regenerate."
  echo
  for pair in "${PAIRS[@]}"; do
    code="${pair%%|*}"
    dev="${pair##*|}"
    read -r vendor product serial <<<"$(probe_attrs "$dev")"
    if [[ "$vendor" == "MISSING" ]]; then
      echo "# SKIP $code — device $dev not present, plug it in and rerun."
      continue
    fi
    if [[ "$vendor" == "ERR" ]]; then
      echo "# SKIP $code — udevadm failed on $dev"
      continue
    fi
    rule_target="parking-gate-$(tr '[:upper:]' '[:lower:]' <<<"$code")"
    attrs="ATTRS{idVendor}==\"$vendor\", ATTRS{idProduct}==\"$product\""
    if [[ "$serial" != "NONE" ]]; then
      attrs="$attrs, ATTRS{serial}==\"$serial\""
    fi
    echo "# $code (was $dev, vendor=$vendor product=$product serial=$serial)"
    echo "SUBSYSTEM==\"tty\", $attrs, SYMLINK+=\"$rule_target\", MODE=\"0660\", GROUP=\"dialout\""
    echo
  done
} > "$tmpfile"

if [[ $DRY_RUN -eq 1 ]]; then
  echo "--- would write to $RULES_FILE ---"
  cat "$tmpfile"
  exit 0
fi

install -m 0644 "$tmpfile" "$RULES_FILE"
echo "wrote $RULES_FILE"
udevadm control --reload-rules
udevadm trigger --subsystem-match=tty
echo "udev reloaded — symlinks active at /dev/parking-gate-*"
echo
echo "NEXT: update gate rows to use the stable symlinks:"
for pair in "${PAIRS[@]}"; do
  code="${pair%%|*}"
  lower="$(tr '[:upper:]' '[:lower:]' <<<"$code")"
  echo "  UPDATE gates SET controller_device='/dev/parking-gate-$lower' WHERE code='$code';"
done
